#include <openssl/sha.h>
#include <unicode/unorm2.h>
#include <unicode/ustring.h>
#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstring>
#include <iomanip>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

struct Err:std::runtime_error{std::string cat;Err(std::string c,std::string m=""):runtime_error(m),cat(std::move(c)){} };
struct V; using O=std::map<std::string,V>; using A=std::vector<V>;
struct V{std::variant<std::nullptr_t,bool,int64_t,std::string,A,O> x; V():x(nullptr){} template<class T> V(T v):x(std::move(v)){} };
static bool utf8(const std::string&s){int32_t n=0;UErrorCode e=U_ZERO_ERROR;u_strFromUTF8(nullptr,0,&n,s.data(),s.size(),&e);return e==U_BUFFER_OVERFLOW_ERROR||U_SUCCESS(e);}
static std::string nfc(const std::string&s){if(!utf8(s))throw Err("INVALID_ENCODING");UErrorCode e=U_ZERO_ERROR;auto*n=unorm2_getNFCInstance(&e);int32_t ulen=0;e=U_ZERO_ERROR;u_strFromUTF8(nullptr,0,&ulen,s.data(),s.size(),&e);if(e!=U_BUFFER_OVERFLOW_ERROR&&U_FAILURE(e))throw Err("INVALID_ENCODING");std::vector<UChar>u(ulen+1);e=U_ZERO_ERROR;u_strFromUTF8(u.data(),u.size(),nullptr,s.data(),s.size(),&e);std::vector<UChar>z(ulen*2+8);e=U_ZERO_ERROR;int32_t zl=unorm2_normalize(n,u.data(),ulen,z.data(),z.size(),&e);if(e==U_BUFFER_OVERFLOW_ERROR){z.resize(zl+1);e=U_ZERO_ERROR;zl=unorm2_normalize(n,u.data(),ulen,z.data(),z.size(),&e);}if(U_FAILURE(e))throw Err("INVALID_ENCODING");int32_t out=0;e=U_ZERO_ERROR;u_strToUTF8(nullptr,0,&out,z.data(),zl,&e);std::string r(out,'\0');e=U_ZERO_ERROR;u_strToUTF8(r.data(),r.size(),nullptr,z.data(),zl,&e);return r;}
static std::string esc(const std::string&s){if(nfc(s)!=s)throw Err("INVALID_ENCODING");std::ostringstream q;q<<'"';for(unsigned char c:s){if(c=='"')q<<"\\\"";else if(c=='\\')q<<"\\\\";else if(c<32)q<<"\\u00"<<std::hex<<std::nouppercase<<std::setw(2)<<std::setfill('0')<<(int)c<<std::dec;else q<<(char)c;}q<<'"';return q.str();}
static std::string canon(const V&v){if(std::holds_alternative<std::nullptr_t>(v.x))return"null";if(auto p=std::get_if<bool>(&v.x))return*p?"true":"false";if(auto p=std::get_if<int64_t>(&v.x))return std::to_string(*p);if(auto p=std::get_if<std::string>(&v.x))return esc(*p);if(auto p=std::get_if<A>(&v.x)){std::string r="[";for(size_t i=0;i<p->size();++i){if(i)r+=",";r+=canon((*p)[i]);}return r+"]";}auto&p=std::get<O>(v.x);std::string r="{";bool f=0;for(auto&[k,x]:p){if(nfc(k)!=k)throw Err("INVALID_ENCODING");if(f)r+=",";f=1;r+=esc(k)+":"+canon(x);}return r+"}";}
class P{const std::string&s;size_t i=0;char pk(){return i<s.size()?s[i]:'\0';}char gt(){return i<s.size()?s[i++]:'\0';}void ws(){while(i<s.size()&&isspace((unsigned char)s[i]))i++;}std::string str(){if(gt()!='"')throw Err("INVALID_ENCODING");std::string r;while(i<s.size()){unsigned char c=gt();if(c=='"')return r;if(c<32)throw Err("INVALID_ENCODING");if(c=='\\'){char e=gt();if(e=='"'||e=='\\'||e=='/')r+=e;else if(e=='b')r+='\b';else if(e=='f')r+='\f';else if(e=='n')r+='\n';else if(e=='r')r+='\r';else if(e=='t')r+='\t';else if(e=='u'){if(i+4>s.size())throw Err("INVALID_ENCODING");unsigned x=0;for(int k=0;k<4;k++){char h=gt();x*=16;if(h>='0'&&h<='9')x+=h-'0';else if(h>='a'&&h<='f')x+=h-'a'+10;else if(h>='A'&&h<='F')x+=h-'A'+10;else throw Err("INVALID_ENCODING");}if(x>=0xD800&&x<=0xDFFF)throw Err("INVALID_ENCODING");if(x<0x80)r+=(char)x;else if(x<0x800){r+=(char)(0xC0|(x>>6));r+=(char)(0x80|(x&63));}else{r+=(char)(0xE0|(x>>12));r+=(char)(0x80|((x>>6)&63));r+=(char)(0x80|(x&63));}}else throw Err("INVALID_ENCODING");}else r+=(char)c;}throw Err("INVALID_ENCODING");}V val(){ws();char c=pk();if(c=='{'){gt();O o;std::set<std::string> nk;ws();if(pk()=='}'){gt();return o;}while(1){ws();std::string k=str();std::string z=nfc(k);if(o.count(k))throw Err("INVALID_ENCODING");if(!nk.insert(z).second)throw Err("INVALID_SCHEMA");ws();if(gt()!=':')throw Err("INVALID_ENCODING");o.emplace(k,val());ws();char d=gt();if(d=='}')break;if(d!=',')throw Err("INVALID_ENCODING");}return o;}if(c=='['){gt();A a;ws();if(pk()==']'){gt();return a;}while(1){a.push_back(val());ws();char d=gt();if(d==']')break;if(d!=',')throw Err("INVALID_ENCODING");}return a;}if(c=='"')return str();if(s.compare(i,4,"true")==0){i+=4;return true;}if(s.compare(i,5,"false")==0){i+=5;return false;}if(s.compare(i,4,"null")==0){i+=4;return V();}size_t b=i;if(c=='-')i++;while(isdigit((unsigned char)pk()))i++;std::string n=s.substr(b,i-b);if(n.empty()||n=="-")throw Err("INVALID_ENCODING");if(n=="-0")throw Err("INVALID_TYPE");if((n[0]=='0'&&n.size()>1)||(n.size()>2&&n[0]=='-'&&n[1]=='0'))throw Err("INVALID_ENCODING");if(pk()=='.'||pk()=='e'||pk()=='E')throw Err("INVALID_TYPE");try{size_t q;long long x=std::stoll(n,&q);if(q!=n.size())throw Err("INVALID_TYPE");return(int64_t)x;}catch(std::out_of_range&){throw Err("INVALID_TYPE");}}public:P(const std::string&x):s(x){}V parse(){if(s.size()>=3&&(unsigned char)s[0]==0xEF&&(unsigned char)s[1]==0xBB&&(unsigned char)s[2]==0xBF)throw Err("INVALID_ENCODING");if(!utf8(s))throw Err("INVALID_ENCODING");V v=val();ws();if(i!=s.size())throw Err("INVALID_ENCODING");return v;}};
static std::string sha(const std::string&s){unsigned char d[SHA256_DIGEST_LENGTH];SHA256((const unsigned char*)s.data(),s.size(),d);std::ostringstream q;for(auto c:d)q<<std::hex<<std::setw(2)<<std::setfill('0')<<(int)c;return q.str();}
static O&obj(V&v){if(!std::holds_alternative<O>(v.x))throw Err("INVALID_SCHEMA");return std::get<O>(v.x);}static const O&obj(const V&v){if(!std::holds_alternative<O>(v.x))throw Err("INVALID_SCHEMA");return std::get<O>(v.x);}static std::string ss(const O&o,const char*k){auto it=o.find(k);if(it==o.end()||!std::holds_alternative<std::string>(it->second.x))throw Err("INVALID_SCHEMA");return std::get<std::string>(it->second.x);}static int64_t ii(const O&o,const char*k){auto it=o.find(k);if(it==o.end()||!std::holds_alternative<int64_t>(it->second.x))throw Err("INVALID_SCHEMA");return std::get<int64_t>(it->second.x);}static void ver(const O&o){auto it=o.find("wire_profile_version");if(it==o.end()||!std::holds_alternative<int64_t>(it->second.x))throw Err("INVALID_SCHEMA");if(std::get<int64_t>(it->second.x)!=1)throw Err("UNSUPPORTED_VERSION");}
static bool leap(int y){return y%4==0&&(y%100!=0||y%400==0);}static void timev(const V&v){if(std::holds_alternative<std::nullptr_t>(v.x))return;if(!std::holds_alternative<std::string>(v.x))throw Err("INVALID_SCHEMA");auto s=std::get<std::string>(v.x);if(s.size()<20||s[4]!='-'||s[7]!='-'||s[10]!='T'||s[13]!=':'||s[16]!=':'||s.back()!='Z')throw Err("INVALID_SCHEMA");auto num=[&](int p,int n){for(int j=0;j<n;j++)if(!isdigit((unsigned char)s[p+j]))throw Err("INVALID_SCHEMA");return std::stoi(s.substr(p,n));};int y=num(0,4),m=num(5,2),d=num(8,2),h=num(11,2),mi=num(14,2),se=num(17,2);int dm[]={0,31,28,31,30,31,30,31,31,30,31,30,31};if(m<1||m>12)throw Err("INVALID_SCHEMA");if(m==2&&leap(y))dm[2]=29;if(d<1||d>dm[m]||h>23||mi>59||se>59)throw Err("INVALID_SCHEMA");if(s.size()>20){if(s[19]!='.')throw Err("INVALID_SCHEMA");size_t n=s.size()-21;if(n<1||n>9)throw Err("INVALID_SCHEMA");for(size_t j=20;j<s.size()-1;j++)if(!isdigit((unsigned char)s[j]))throw Err("INVALID_SCHEMA");if(s[s.size()-2]=='0')throw Err("INVALID_SCHEMA");}}
static void ident(const std::string&s){if(s.empty()||s.size()>255||nfc(s)!=s)throw Err("INVALID_SCHEMA");for(unsigned char c:s)if(c<32)throw Err("INVALID_SCHEMA");}
static void closed(const O&o,std::initializer_list<const char*>ks){std::set<std::string>a;for(auto k:ks)a.insert(k);for(auto&[k,v]:o)if(!a.count(k))throw Err("UNSUPPORTED_REQUIRED_FIELD");for(auto k:a)if(!o.count(k))throw Err("INVALID_SCHEMA");}
static void frontier(const O&o){closed(o,{"wire_profile_version","schema_version","contiguous","gaps"});ver(o);if(ii(o,"schema_version")<0)throw Err("INVALID_SCHEMA");auto ci=o.find("contiguous"),gi=o.find("gaps");if(!std::holds_alternative<O>(ci->second.x)||!std::holds_alternative<O>(gi->second.x))throw Err("INVALID_SCHEMA");for(auto&[k,v]:std::get<O>(ci->second.x)){ident(k);if(!std::holds_alternative<int64_t>(v.x)||std::get<int64_t>(v.x)<0)throw Err("INVALID_SEQUENCE");}for(auto&[k,v]:std::get<O>(gi->second.x)){ident(k);if(!std::holds_alternative<A>(v.x))throw Err("INVALID_SEQUENCE");int64_t last=0,base=0;auto z=std::get<O>(ci->second.x).find(k);if(z!=std::get<O>(ci->second.x).end())base=std::get<int64_t>(z->second.x);for(auto&x:std::get<A>(v.x)){if(!std::holds_alternative<int64_t>(x.x))throw Err("INVALID_SEQUENCE");auto n=std::get<int64_t>(x.x);if(n<=base||n<=last)throw Err("INVALID_SEQUENCE");last=n;}}}
static void durable(O&o,bool integrity){closed(o,{"wire_profile_version","record_id","record_type","vk_identity_id","origin_node_id","origin_sequence","state_class","provenance","payload","parents","claim_class","admission_state","schema_version","observed_at","integrity_digest"});ver(o);for(auto k:{"record_id","record_type","vk_identity_id","origin_node_id"})ident(ss(o,k));auto q=ii(o,"origin_sequence");if(q<1)throw Err("INVALID_SEQUENCE");auto sc=ss(o,"state_class");std::set<std::string>cs={"SHARED_REPLICATED","NODE_LOCAL","TRANSIENT","SECRETS","DERIVED_REBUILDABLE"};if(!cs.count(sc))throw Err("INVALID_ENUM");auto&p=o.at("parents");if(!std::holds_alternative<A>(p.x))throw Err("INVALID_SCHEMA");std::string last;for(auto&x:std::get<A>(p.x)){if(!std::holds_alternative<std::string>(x.x))throw Err("INVALID_LINEAGE");auto z=std::get<std::string>(x.x);ident(z);if(z==ss(o,"record_id")||(!last.empty()&&z<=last))throw Err("INVALID_LINEAGE");last=z;}timev(o.at("observed_at"));auto dg=ss(o,"integrity_digest");if(dg.size()!=64||!std::all_of(dg.begin(),dg.end(),[](char c){return isdigit((unsigned char)c)||(c>='a'&&c<='f');}))throw Err("INVALID_INTEGRITY");if(integrity){O c=o;c.erase("integrity_digest");if(sha(canon(V(c)))!=dg)throw Err("INVALID_INTEGRITY");}}
static std::string relation(const O&a,const O&b){auto&ac=std::get<O>(a.at("contiguous").x);auto&bc=std::get<O>(b.at("contiguous").x);std::set<std::string>ks;for(auto&x:ac)ks.insert(x.first);for(auto&x:bc)ks.insert(x.first);bool ge=1,le=1,g=0,l=0;for(auto&k:ks){int64_t x=ac.count(k)?std::get<int64_t>(ac.at(k).x):0,y=bc.count(k)?std::get<int64_t>(bc.at(k).x):0;ge&=x>=y;le&=x<=y;g|=x>y;l|=x<y;}if(ge&&!g&&le&&!l)return"EQUAL";if(ge&&g)return"DOMINATES";if(le&&l)return"DOMINATED_BY";return"DIVERGED";}
int main(int argc,char**argv){try{if(argc<3)throw std::runtime_error("usage: mode json");std::string mode=argv[1],s=argv[2];P p(s);V v=p.parse();std::string c=canon(v);if(mode=="canonical"){std::cout<<c<<"\n"<<sha(c)<<"\n";return 0;}O&o=obj(v);if(mode=="durable"){durable(o,true);std::cout<<"ACCEPTED\n"<<c<<"\n";return 0;}if(mode=="frontier"){frontier(o);std::cout<<"ACCEPTED\n"<<c<<"\n"<<sha(c)<<"\n";return 0;}if(mode=="checkpoint"){closed(o,{"wire_profile_version","checkpoint_id","vk_identity_id","frontier","canonical_state_digest","manifest_digest","schema_version"});ver(o);ident(ss(o,"checkpoint_id"));ident(ss(o,"vk_identity_id"));frontier(obj(o.at("frontier")));for(auto k:{"canonical_state_digest","manifest_digest"}){auto d=ss(o,k);if(d.size()!=64||!std::all_of(d.begin(),d.end(),[](char x){return isdigit((unsigned char)x)||(x>='a'&&x<='f');}))throw Err("INVALID_SCHEMA");}std::cout<<"ACCEPTED\n"<<c<<"\n"<<sha(c)<<"\n";return 0;}if(mode=="recon"){closed(o,{"wire_profile_version","reconciliation_id","vk_identity_id","input_record_ids","result","provenance","policy","authority","schema_version"});ver(o);auto&a=std::get<A>(o.at("input_record_ids").x);if(a.size()<2)throw Err("INVALID_SCHEMA");std::string last;for(auto&x:a){if(!std::holds_alternative<std::string>(x.x))throw Err("INVALID_SCHEMA");auto z=std::get<std::string>(x.x);if(!last.empty()&&z<=last)throw Err("INVALID_SCHEMA");last=z;}std::cout<<"ACCEPTED\n"<<c<<"\n"<<sha(c)<<"\n";return 0;}if(mode=="relation"){auto&a=obj(o.at("a")),&b=obj(o.at("b"));frontier(a);frontier(b);std::cout<<relation(a,b)<<"\n";return 0;}throw std::runtime_error("mode");}catch(const Err&e){std::cout<<e.cat<<"\n";return 2;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 3;}}
